auth:
  port: 8081
  migration-path: "file://migrations/auth"
  secret-key: "VxCDGAeugvEa6jvBiFYcOboddRGKydns"

postgres:
  host: "localhost"
  port: 5432
  username: "root"
  password: "1234"
  database: "postgres"