auth:
  port: 8081
  migration-path: "file://migrations/auth"
  secret-key: "VxCDGAeugvEa6jvBiFYcOboddRGKydns"

postgres:
  host: "localhost"
  port: 5432
  username: "root"
  password: "1234"
  database: "postgres"

kafka:
  host: "localhost"
  port: 9092
  brokers:
    - 0.0.0.0:9092


order:
  port: 8082
  migration-path: "file://migrations/order"
  secret-key: "VxCDGAeugvEa6jvBiFYcOboddRGKydns"